name: PyTest

env:
  CLIENT_SECRET: ''
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 3

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        python-version:
          #          - "3.11"
          - "3.12"
    name: PyTest on
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-dotenv

      - name: Create paths logs and secrets
        run: |
          mkdir logs
          mkdir data-project/secrets

      - name: Running Pytest on src
        run: pytest